# Generated by Django 5.0.2 on 2024-04-24 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='mensagem',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
